### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Hellzbellz123** [cguz/java-to-rust#14]
Im not seeming to understand how this works i guess, but when running this on example.java it creates a new directory called output but it doesnt actually write new files in the folder, my guess is the tool is failing to translate it, does this produce logs by chance?

![image](https://user-images.githubusercontent.com/31550512/148868212-b2462005-4225-45be-9047-44bd86e4297c.png)

```
import java.io.File;
import java.lang.reflect.Field;
import java.util.Arrays;

import net.minecraft.client.main.Main;

public class Start
{
    public static void main(String[] args)
    {
        Main.main(concat(new String[] {"--version", "mcp", "--accessToken", "0", "--assetsDir", "assets", "--assetIndex", "1.8", "--userProperties", "{}"}, args));
    }

    public static <T> T[] concat(T[] first, T[] second)
    {
        T[] result = Arrays.copyOf(first, first.length + second.length);
        System.arraycopy(second, 0, result, first.length, second.length);
        return result;
    }
}
```

**Comment by cguz** [comment]
Hi @Hellzbellz123 , 

I do not see any error:

![image](https://user-images.githubusercontent.com/15159632/148881392-60170099-8c40-4064-b4c0-3db5b0f42cc9.png)

It generates the folder and the files. 

Please, clone the repo and follow the "How to build it" steps

Cheers!

**Comment by Hellzbellz123** [comment]
Does moving the java2rust jar break it? I should be running it inside the mvn package folder?,
This is how I built and got to trying to translate
1st cloned the repo to ~/source//java-to-rust
2nd I cdd in and ran mvn pkg, I then moved the jar file to my downloads folder into mcp940 source and tried above commands, I followed the bold instructions

**Comment by cguz** [comment]
No. 

2. What did you get when you run the command?:

mvn package 

2.  from which folder do you get the jar file?

3. It is not necessary to move the jar file. Only execute it and put the folder with -d [PATH TO FOLDER OR FILE]

**Comment by Hellzbellz123** [comment]
When I get home I will upload the mvn pkg log
